import { ProductCard } from "../types";

export const PRODUCTS: ProductCard[] = [
  {
    id: 1,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 2,
    name: "Pixel Watch 2",
    price: 560000,
    description: "Good Watch",
    category: "Watch",
  },
  {
    id: 3,
    name: "Samsung S23 Ultra",
    price: 560000,
    description: "Good Watch",
    category: "Watch",
  },
  {
    id: 4,
    name: "Xiaomi 14 Ultra",
    price: 560000,
    description: "Good Watch",
    category: "Watch",
  },
  {
    id: 5,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 6,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 7,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 8,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 9,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 10,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 11,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 12,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 13,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 14,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 15,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 16,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 17,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 18,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 19,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
  {
    id: 20,
    name: "Iphone 13 Pro Max",
    price: 200000,
    description: "Good telephone",
    category: "Smartphone",
  },
];
